---
deployment:
  tasks:
    - export DEPLOYPATH=/home/idarahco/public_html/idarah786.com
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R backend $DEPLOYPATH
    - /bin/cp -R frontend $DEPLOYPATH
    - /bin/cp main.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH || true
