runtime: python39
service: default

env_variables:
  PRODUCTION: "true"
  # Cloud SQL Configuration
  # Replace these values with your actual Cloud SQL details
  DB_HOST: "127.0.0.1"  # Use 127.0.0.1 for Cloud SQL Proxy
  DB_USER: "madani_user"
  DB_PASSWORD: "YOUR_DB_PASSWORD_HERE"  # Replace with actual password
  DB_NAME: "madani_moktob"
  DB_PORT: "3306"

# Scale down to zero when not in use (saves costs)
automatic_scaling:
  min_instances: 0
  max_instances: 10

# Health check configuration
readiness_check:
  path: "/api/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2 